name: auto_provider_generator
description: Code generator for @AutoProvid annotation, enabling automatic Bloc state management With lazy singletons GetIt and auto routing integration.
homepage: https://github.com/mohamadalghanem474/auto_provider
repository: https://github.com/mohamadalghanem474/auto_provider
issue_tracker: https://github.com/mohamadalghanem474/auto_provider/issues
documentation: https://github.com/mohamadalghanem474/auto_provider#readme
version: 0.0.8
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  source_gen: ^4.0.2
  analyzer: ^8.1.0
  build: ^4.0.2
  auto_provider_annotation: ^0.0.1
  glob: ^2.1.2

dev_dependencies:
  build_runner: ^2.4.0

topics:
  - bloc
  - cubit
  - state-management
  - getit
  - auto-router