name: auto_provider_generator
publish_to: none
description: Code generator for @Screen annotation
version: 1.0.0
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  source_gen: ^4.0.2
  analyzer: ^8.1.0
  build: ^4.0.2
  auto_provider_annotation:
    path: ../auto_provider_annotation
  glob: ^2.1.2

dev_dependencies:
  build_runner: ^2.4.0
