name: auto_provider_annotation
description: Annotation package for auto_provider_generator code generation
homepage: https://github.com/mohamadalghanem474/auto_provider
repository: https://github.com/mohamadalghanem474/auto_provider
issue_tracker: https://github.com/mohamadalghanem474/auto_provider/issues
documentation: https://github.com/mohamadalghanem474/auto_provider#readme
version: 0.0.13

environment:
  sdk: ">=3.0.0 <4.0.0"

topics:
  - bloc
  - cubit
  - state-management
  - getit
  - auto-router

screenshots:
  - description: The auto_provider_annotation package logo.
    path: ../screenshots/logo.png
